# Generated by Django 3.2.3 on 2021-05-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Jnr Developer', 'Jnr Developer'), ('Accountant', 'Accountant'), ('Sales Manager', 'Sales Manager')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
